// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfRr479r7OmwOnM4sVakHXuHjU1LIn3Jo',
    appId: '1:312389703114:web:239fc5ac2ca7441e21eb33',
    messagingSenderId: '312389703114',
    projectId: 'arm-chair-quaterback',
    authDomain: 'arm-chair-quaterback.firebaseapp.com',
    storageBucket: 'arm-chair-quaterback.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5rXqVUdmtNPTdaTdzFgjArDiMLv42P0o',
    appId: '1:312389703114:android:dbe6d6e9cfb459d121eb33',
    messagingSenderId: '312389703114',
    projectId: 'arm-chair-quaterback',
    storageBucket: 'arm-chair-quaterback.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSMdv0tjd3z5M3T0CdjJXctRKKxGFQAc8',
    appId: '1:312389703114:ios:a0943262d0f1336121eb33',
    messagingSenderId: '312389703114',
    projectId: 'arm-chair-quaterback',
    storageBucket: 'arm-chair-quaterback.firebasestorage.app',
    iosBundleId: 'com.ftxapp.armChairQuaterback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSMdv0tjd3z5M3T0CdjJXctRKKxGFQAc8',
    appId: '1:312389703114:ios:65af999c871e232921eb33',
    messagingSenderId: '312389703114',
    projectId: 'arm-chair-quaterback',
    storageBucket: 'arm-chair-quaterback.firebasestorage.app',
    iosBundleId: 'com.example.armChairQuaterback.RunnerTests',
  );
}
