const Map<String, String> en_US = {
  'news': 'NEWS',
  'picks': 'PICKS',
  'team': 'TEAM',
  'leagues': 'LEAGUES',
  "gameNameFgm": "FGM",
  "gameNameFga": "FGA",
  "gameNameTgm": "3PM",
  "gameNameTga": "3PA",
  "gameNameFtm": "FTM",
  "gameNameFta": "FTA",
  "gameNameReb": "REB",
  "gameNameAst": "AST",
  "gameNameStl": "STL",
  "gameNameBlk": "BLK",
  "gameNameFoul": "FOUL",
  "gameNameTo": "TO",
  "gameNamePts": "PTS",
  "gameTabNews": "News",
  "gametabPicks": "PICKS",
  "gametabStocks": "Stocks",
  "gametabTeam": "MY TEAM",
  "gametabScores": "SCORES",
  "newsTabTickers": "NEWS TICKERS",
  "newsTabNews": "NEWS",
  "newsTabMore": "More News",
  "newsTabReview": "Review",
  "newsTipsInput": "Post your reply",
  "newsButtonReply": "reply",
  "newsButtonMore": "more",
  "newsButtonFold": "fold",
  "newsTipsFold": "No more",
  "newsTabStats": "Stats",
  "newsTabStanding": "Standings",
  "newsButtonPlayer": "Player",
  "newsButtonTeam": "Team",
  "newsTabRank": "Rank",
  "gameMeanPts": "Points",
  "gameMeanAst": "Assists",
  "gameMeanBlk": "Blocks",
  "gameMeanFgp": "FG%",
  "gameMeanReb": "Rebounds",
  "gameMeanStl": "Steals",
  "gameMeanFtp": "Free Throw Percent",
  "gameMeanTpp": "Three Pointer Percent",
  "gameMeanTo": "Turnovers",
  "gameMeanReseason": "Regular Season",
  "gameMeanPoseason": "Post Season",
  "newsButtonEastern": "Eastern",
  "newsButtonWestern": "Western",
  "newsTabType": "type",
  "newsTabSeason": "Season",
  "pickTabRank": "RANK",
  "picktabHistory": "My Picks",
  "pickTabRewards": "Pick Rewards",
  "pickTabMnl": "More&Less",
  "pickButtonMore": "MORE",
  "pickButtonLess": "LESS",
  "pickButtonConfirm": "CONFIRM",
  "gameTapinfo": "INFO",
  "pickTapBenefits": "Total Win",
  "pickTapName": "Name",
  "pickTapRank": "Rank",
  "pickTipsSelect": "How will {0} play with {0} team",
  "gameNameJetton": "jetton",
  "pickWinTimes": "win",
  "pickSuccess": "success rate",
  "gameTapPick": "Pick",
  "gameTapTeam": "Team",
  "pickRankCon": "Rank",
  "pickRankReward": "Reward",
  "pickrRankNum": "{}th Rank",
  "pickrRankIntro": "Pick more Pick right",
  "pickRankBox": "BOX",
  "pickRankCoin": "JETTON",
  "pickTapRankRaward": "RANK REWARD",
  "pickButtonGet": "GET",
  "pickButtonReceiveAll": "RECEIVE ALL",
  "gameFullNamePts": "Points per game",
  "gameFullNameAst": "Assists per game",
  "gameFullNameReb": "Rebounds per game",
  "gameFullNameFGP": "Field goal percentage",
  "gameFullNameBlk": "Block shot",
  "gameFullNameStl": "Steals per game",
  "gameFullNameFtp": "Free throw percentage",
  "gameFullNameTpa": "Three-point shot attempts",
  "gameFullNameTpp": "Three-point shot percentage",
  "gameFullNameTo": "Turnovers",
  "managerHi": "Hi,{0}",
  "managerTipsIntro1": "You haven't started the Battle Game yet",
  "managerTipsIntro2": "Your match records for today",
  "managerNameBattleTimes": "Battle",
  "managerNameTrainingTimes": "Training",
  "cardpackButtonOpen": "OPEN",
  "tieButtonOpen": "TIE",
  "managerNameTrainingLevel": "Training Level",
  "managerTabTeam": "Team",
  "managerTabMyTeam": "MY TEAM",
  "teamTabLineUp": "LineUp",
  "teamTabPlayerBag": "Player Bag",
  "gameNameOvr": "OVR",
  "gameMeanSalaryCap": "Salary Cap",
  "gameMeanTeamStamina": "Team Stamina Avg",
  "teamTipsRest": "rest once",
  "teamMeanMain": "Main",
  "playerNameSalary": "SAL",
  "playerNameStamina": "STA",
  "playerButtonAddStamina": "add STA",
  "teamMeanSubstitiute": "Substitiute",
  "teamNameSubstitiute": "Sub",
  "teamButtonAddPlayer": "Add Player",
  "teamTipsUnlcok": "Team Lv.{0} unlock",
  "teamTabsAddStamina": "Add Stamina",
  "teamTipsTeamRest":
      "At the end of the countdown, the whole team will regain their stamina once. Do you want to recover your stamina in advance",
  "teamMeanCost": "Cost",
  "managerTabCardPack": "Battle Win CardPack",
  "gameNameTp": "3PT",
  "gameMeanMe": "ME",
  "gameMeanOpp": "OPPONMENT",
  "gameMeanRate": "Win Rate",
  "gameNameSt": "1ST",
  "gameNameNd": "2ND",
  "gameNameRd": "3RD",
  "gameNameTh": "4TH",
  "gameMeanPlayer": "Stats",
  "gameMeanTeam": "Team",
  "gameButtonback": "Back",
  "gameMeanTrade": "Today Trade",
  "gameMeanPrice": "Team Price",
  "gameNameBag": "bag",
  "gameTabBuy": "BUY",
  "gameTabSell": "SELL",
  "gameButtonBuy": "Buy",
  "gameButtonSell": "Sell",
  "gameTabPlayerInfo": "Info",
  "gameNameAge": "AGE",
  "gameNameHeight": "HEIGHT",
  "gameNameWeight": "WEIGHT",
  "gameNameExp": "EXP",
  "gameTabSummary": "Summary",
  "gameTabLogs": "Logs",
  "gameTabGame": "Game",
  "gameTabL5": "Last  5 Games",
  "gameTabSeasonAvg": "Season AVG",
  "gameTabL5Avg": "Last 5 AVG",
  "gameTabBetSelection": "Betting selections",
  "gameTabGameGrade": "GameGrade",
  "gameMeanSeasonAvg": "Season Averge",
  "gameNameScore": "Score",
  "gameButtonStarUp": "StarUp",
  "gameNameAbility": "Ability",
  "gameNamePotential": "Potential",
  "gameNameSuccess": "Success Rate",
  "gameNameGrade": "Grade",
  "gameNameStar": "Star",
  "gameNameSelected": "Selected",
  // "gameButtonStarUp": "Star Up",
  "gameTabSuccess": "Succeeded",
  "gameTabFail": "Failed",
  "pickTabLineUp": "Pick Line Up",
  "pickMeanFlex": "Flex Play",
  "pickMeanPower": "Power Play",
  "pickNameCorrect": "correct",
  "pickNameSelected": "Picks",
  "pickNameToWin": "To Win",
  "pickNameStreak": "Streak",
  "pickNameStreakBonus": "Streak Bonus",
  "pickTipsFlex": "Hit {0} out of {0} in the line up",
  "pickButtonClear": "Clear All",
  "pickTipsLackMoney": "short of money",
  "pickNameResult": "Result",
  "pickNameProcess": "In Process",
  "userButtonProfile": "Profile",
  "userButtonMessage": "Message",
  "userButtonSetting": "Setting",
  "userButtonAccount": "Account",
  "userNameTeamLevel": "TeamLevel",
  "userNameWinRate": "Win Rate",
  "userNameWinTimes": "Streak Won",
  "userNameWinStreak": "Win Streak",
  "userNameCurrentCup": "Current",
  "userNameBestCup": "Best",
  "userNamePickHistory": "OPEN",
  "userNameStreakPick": "Stakes Won",
  "uesrNameNewsPick": "CLOSED",
  "uesrNameLastInterrupt": "Last Streak Record",
  "userNameNick": "Display name",
  "userNameBirthday": "Birthday",
  "userNameAbout": "About you",
  "userButtonSave": "Save",
  "userButtonReport": "Report",
  "userButtonBlock": "Block",
  "userButtonRelease": "Release",
  "userButtonShare": "Share to other",
  "userTabNewFeatures": "New features",
  "userButtonLanguages": "Languages",
  "userButtonMusic": "Music",
  "userButtonSound": "Sound",
  "userButtonNotification": "Notification",
  "userButtonSwitch": "Switch account",
  "userButtonLogout": "Log out",
  "userButtonAddAccount": "Add  new account",
  "trainNameOwn": "Balls",
  "tranMeanTask": "Daily Task",
  "newsTabGame": "Game news",
  "newsTabSchedule": "Schedule",
  "newsTabInjuries": "Injuries",
  "newsTabDraft": "Draft",
  "newsTabStreakPicks": "Today's Streak Picks",
  "newsTabTrade": "Trade",
  "newsTabTopRumor": "Top Rumor",
  "newsTabPopularPlayer": "Popular player",
  "newsTabLatest": "Lastest",
  "newsNameTp": "3 Points",
  "pickTabTask": "Daily Task",
  "pickTipsTask": "Select {0} player can get the reward",
  "pickButtonCheck": "Check Line Up",
  "pickButtonGo": "Go",
  "teamButtonNotice": "Notices",
  "teamTabGift": "Free Gift",
  "teamButtonGift": "Receive",
  "teamButtonBattlePass": "Trophy Road",
  "teamButtonUnlocked": "Unlocked",
  "teamButtonGoMatch": "Go To Match",
  "teamTabMatch": "MATCH GAME",
  "teamButtonMatch": "MATCH",
  "teamTabTrainLevel": "DEGREE OF TRAINING",
  "teamTabTrainBuff": "TRAINING BUFF",
  "teamTabTrain": "TRAINING",
  "teamTipsBuffNone": "NONE",
  "teamButtonStart": "START",
  "teamTabTeamPower": "TEAM POWER",
  "teamButtonLineUp": "LINE UP",
  "gameTabManager": "Manager",
  "gameTabMe": "me",
  "pickNameTotalPoints": "Total Points",
  "pickNameTotalRebounds": "Total Rebounds",
  "pickNameTotalAssists": "Total Assits",
  "pickNameTotalPNA": "Total Points+Assists",
  "pickButtonEdit": "Edit",
  "pickTipsAdd": "Add player pick",
  "pickNameCost": "Wager",
  "pickButtonDone": "Done",
  "pickTipsSuccess": "PICK SUCCESS",
  "pickButtonContinue": "CONTINUE",
  "scoreTipsFinal": "Final",
  "scoreTipsResult": "Result",
  "gameInfoCongratulation": "CONGRATULATION",
  "gameInfoGetJetton": "You have won {0} jetton",
  "scoreTipsGaming": "Gaming",
  "scoreButtonWin": "WIN",
  "scoreTipsRate": "Support rate",
  "nbaTeamMeanOverview": "OVERVIEW",
  "nbaTeamMeanRoster": "ROSTER",
  "nbaTeamMeanStats": "STATS",
  "nbaTeamMeanLog": "LOG",
  "nbaTeamMeanEastern": "IN EASTERN",
  "nbaTeamMeanWestern": "IN WESTERN",
  "nbaTeamTabAvg": "Season Avg",
  "nbaTeamNamePpg": "PPG",
  "nbaTeamNameRpg": "RPG",
  "nbaTeamNameApg": "APG",
  "nbaTeamNameOppg": "OPPG",
  "nbaTeamTabOppg": "RECENT",
  "nbaTeamTabOutcome": "OUTCOME",
  "pickTipsReview": "Post your prediction",
  "nbaTeamMeanForward": "FORWARD",
  "nbaTeamMeanGuard": "GUARD",
  "nbaTeamMeanCenter": "CENTER",
  "nbaTeamMeanPlayerCount": "PLAYER COUNT",
  "nbaTeamMeanLeader": "TEAM LEADERS",
  "nbaTeamMeanTeamStats": "TEAM STATS",
  "nbaTeamMeanOvr": "OVR",
  "nbaTeamMeanHome": "HOME",
  "nbaTeamMeanAway": "AWAY",
  "gameStatsMeanExhausted": "Exhausted",
  "gameStatsMeanTired": "Tired",
  "gameStatsMeanNormal": "Normal",
  "gameStatsMeanGood": "Good",
  "gameStatsMeanEnergetic": "Energetic",
  "gameStatsMeanBoundless": "Boundless",
  "gameMeanRegular": "REG",
  "gameMeanPost": "POS",
  "gameMeanCareer": "CAREER",
  "gameNameAvg": "AVG",
  "gameNameHt": "HT",
  "gameNameWt": "WT",
  // "gameNameExp": "EXP"
};
// const Map<String, String> en_US = {
//   'news': 'NEWS',
//   'picks': 'PICKS',
//   'team': 'TEAM',
//   'leagues': 'LEAGUES',
//   "gameNameFgm": "FGM",
//   'gameNameFga': 'FGA'
// };
