// ignore_for_file: file_names

import 'package:arm_chair_quaterback/common/langs/lang_key.dart';

// ignore: non_constant_identifier_names
Map<String, String> en_US = {
  LangKey.gameNameFgm: "FGM",
  LangKey.gameNameFga: "FGA",
  LangKey.gameNameTgm: "3PM",
  LangKey.gameNameTga: "3PA",
  LangKey.gameNameFtm: "FTM",
  LangKey.gameNameFta: "FTA",
  LangKey.gameNameReb: "REB",
  LangKey.gameNameAst: "AST",
  LangKey.gameNameStl: "STL",
  LangKey.gameNameBlk: "BLK",
  LangKey.gameNameFoul: "FOUL",
  LangKey.gameNameTo: "TO",
  LangKey.gameNamePts: "PTS",
  LangKey.gameTabNews: "Home",
  LangKey.gametabPicks: "Picks",
  LangKey.gametabStocks: "Stocks",
  LangKey.gametabTeam: "MY TEAM",
  LangKey.gametabScores: "Scores",
  LangKey.newsTabTickers: "NEWS TICKERS",
  LangKey.newsTabNews: "NEWS",
  LangKey.newsTabMore: "More News",
  LangKey.newsTabReview: "Review",
  LangKey.newsTipsInput: "Post your reply",
  LangKey.newsButtonReply: "reply",
  LangKey.newsButtonMore: "more",
  LangKey.newsButtonFold: "fold",
  LangKey.newsTipsFold: "No more",
  LangKey.newsTabStats: "Stats",
  LangKey.newsTabStanding: "Standings",
  LangKey.newsButtonPlayer: "Player",
  LangKey.newsButtonTeam: "Team",
  LangKey.newsTabRank: "Rank",
  LangKey.gameMeanPts: "Points",
  LangKey.gameMeanAst: "Assists",
  LangKey.gameMeanBlk: "Blocks",
  LangKey.gameMeanFgp: "FG%",
  LangKey.gameMeanReb: "Rebounds",
  LangKey.gameMeanStl: "Steals",
  LangKey.gameMeanFtp: "Free Throw Percent",
  LangKey.gameMeanTpp: "Three Pointer Percent",
  LangKey.gameMeanTo: "Turnovers",
  LangKey.gameMeanReseason: "Regular Season",
  LangKey.gameMeanPoseason: "Post Season",
  LangKey.newsButtonEastern: "Eastern",
  LangKey.newsButtonWestern: "Western",
  LangKey.newsTabType: "type",
  LangKey.newsTabSeason: "Season",
  LangKey.pickTabRank: "RANK",
  LangKey.pickTabHistory: "My Picks",
  LangKey.pickTabRewards: "Pick Rewards",
  LangKey.pickTabMnl: "More&Less",
  LangKey.pickButtonMore: "MORE",
  LangKey.pickButtonLess: "LESS",
  LangKey.pickButtonConfirm: "CONFIRM",
  LangKey.gameTapInfo: "INFO",
  LangKey.pickTapBenefits: "Total Win",
  LangKey.pickTapName: "Name",
  LangKey.pickTapRank: "Rank",
  LangKey.pickTipsSelect: "How will {0} play with {0} team",
  LangKey.gameNameJetton: "jetton",
  LangKey.pickWinTimes: "win",
  LangKey.pickSuccess: "success rate",
  LangKey.gameTapPick: "Pick",
  LangKey.gameTapTeam: "Team",
  LangKey.pickRankCon: "Rank",
  LangKey.pickRankReward: "Reward",
  LangKey.pickrRankNum: "{}th Rank",
  LangKey.pickrRankIntro: "Pick more Pick right",
  LangKey.pickRankBox: "BOX",
  LangKey.pickRankCoin: "JETTON",
  LangKey.pickTapRankRaward: "RANK REWARD",
  LangKey.pickButtonGet: "GET",
  LangKey.pickButtonReceiveAll: "RECEIVE ALL",
  LangKey.gameFullNamePts: "Points per game",
  LangKey.gameFullNameAst: "Assists per game",
  LangKey.gameFullNameReb: "Rebounds per game",
  LangKey.gameFullNameFGP: "Field goal percentage",
  LangKey.gameFullNameBlk: "Block shot",
  LangKey.gameFullNameStl: "Steals per game",
  LangKey.gameFullNameFtp: "Free throw percentage",
  LangKey.gameFullNameTpa: "Three-point shot attempts",
  LangKey.gameFullNameTpp: "Three-point shot percentage",
  LangKey.gameFullNameTo: "Turnovers",
  LangKey.managerHi: "Hi,{0}",
  LangKey.managerTipsIntro1: "You haven't started the Battle Game yet",
  LangKey.managerTipsIntro2: "Your match records for today",
  LangKey.managerNameBattleTimes: "Battle",
  LangKey.managerNameTrainingTimes: "Training",
  LangKey.cardpackButtonOpen: "OPEN",
  LangKey.tieButtonOpen: "TIE",
  LangKey.managerNameTrainingLevel: "Training Level",
  LangKey.managerTabTeam: "Team",
  LangKey.managerTabMyTeam: "MY TEAM",
  LangKey.teamTabLineUp: "LineUp",
  LangKey.teamTabPlayerBag: "Player Bag",
  LangKey.gameNameOvr: "OVR",
  LangKey.gameMeanSalaryCap: "SALARY CAP",
  LangKey.gameMeanTeamStamina: "Team Stamina Avg",
  LangKey.teamTipsRest: "rest once",
  LangKey.teamMeanMain: "Main",
  LangKey.playerNameSalary: "SAL",
  LangKey.playerNameStamina: "STA",
  LangKey.playerButtonAddStamina: "add STA",
  LangKey.teamMeanSubstitiute: "Substitiute",
  LangKey.teamNameSubstitiute: "Sub",
  LangKey.teamButtonAddPlayer: "Add Player",
  LangKey.teamTipsUnlcok: "Team Lv.{0} unlock",
  LangKey.teamTabsAddStamina: "Add Stamina",
  LangKey.teamTipsTeamRest:
      "At the end of the countdown, the whole team will regain their stamina once. Do you want to recover your stamina in advance",
  LangKey.teamMeanCost: "Cost",
  LangKey.managerTabCardPack: "Battle Win CardPack",
  LangKey.gameNameTp: "3PT",
  LangKey.gameMeanMe: "ME",
  LangKey.gameMeanOpp: "OPPONMENT",
  LangKey.gameMeanRate: "Win Rate",
  LangKey.gameNameSt: "1ST",
  LangKey.gameNameNd: "2ND",
  LangKey.gameNameRd: "3RD",
  LangKey.gameNameTh: "4TH",
  LangKey.gameMeanPlayer: "Stats",
  LangKey.gameMeanTeam: "Team",
  LangKey.gameButtonback: "Back", // 校正拼写错误
  LangKey.gameMeanTrade: "Today Trade",
  LangKey.gameMeanPrice: "Team Price",
  LangKey.gameNameBag: "bag",
  LangKey.gameTabBuy: "BUY",
  LangKey.gameTabSell: "SELL",
  LangKey.gameButtonBuy: "Buy",
  LangKey.gameButtonSell: "Sell",
  LangKey.gameTabPlayerInfo: "Info",
  LangKey.gameNameAge: "AGE",
  LangKey.gameNameHeight: "HEIGHT",
  LangKey.gameNameWeight: "WEIGHT",
  LangKey.gameNameExp: "EXP",
  LangKey.gameTabSummary: "Summary",
  LangKey.gameTabLogs: "Logs",
  LangKey.gameTabGame: "Game",
  LangKey.gameTabL5: "Last 5 Games",
  LangKey.gameTabSeasonAvg: "Season AVG",
  LangKey.gameTabL5Avg: "Last 5 AVG",
  LangKey.gameTabBetSelection: "Betting selections",
  LangKey.gameTabGameGrade: "GameGrade",
  LangKey.gameMeanSeasonAvg: "Season Average", // 校正拼写错误
  LangKey.gameNameScore: "Score",
  LangKey.gameButtonStarUp: "StarUp",
  LangKey.gameNameAbility: "Ability",
  LangKey.gameNamePotential: "Potential",
  LangKey.gameNameSuccess: "Success",
  LangKey.gameNameGrade: "Grade",
  LangKey.gameNameStar: "Star",
  LangKey.gameNameSelected: "Selected",
  LangKey.gameTabSuccess: "Succeeded",
  LangKey.gameTabFail: "Failed",
  LangKey.pickTabLineUp: "PICK LINE UP",
  LangKey.pickMeanFlex: "Flex Play",
  LangKey.pickMeanPower: "Power Play",
  LangKey.pickNameCorrect: "correct",
  LangKey.pickNameSelected: "Picks",
  LangKey.pickNameToWin: "To Win",
  LangKey.pickNameStreak: "Streak",
  LangKey.pickNameStreakBonus: "Streak Bonus",
  LangKey.pickTipsFlex: "Hit {0} out of {0} in the line up",
  LangKey.pickButtonClear: "pickButtonClearAll",
  LangKey.pickTipsLackMoney: "short of money",
  LangKey.pickNameResult: "Result",
  LangKey.pickNameProcess: "In Process",
  LangKey.userButtonProfile: "Profile",
  LangKey.userButtonMessage: "Message",
  LangKey.userButtonSetting: "Setting",
  LangKey.userButtonAccount: "Account",
  LangKey.userNameTeamLevel: "TeamLevel",
  LangKey.userNameWinRate: "Win Rate",
  LangKey.userNameWinTimes: "Streak Won",
  LangKey.userNameWinStreak: "Win Streak",
  LangKey.userNameCurrentCup: "Current",
  LangKey.userNameBestCup: "Best",
  LangKey.userNamePickHistory: "OPEN",
  LangKey.userNameStreakPick: "Stakes Won",
  LangKey.uesrNameNewsPick: "CLOSED",
  LangKey.uesrNameLastInterrupt: "Last Streak Record",
  LangKey.userNameNick: "Display name",
  LangKey.userNameBirthday: "Birthday",
  LangKey.userNameAbout: "About you",
  LangKey.userButtonSave: "Save",
  LangKey.userButtonReport: "Report",
  LangKey.userButtonBlock: "Block",
  LangKey.userButtonRelease: "Release",
  LangKey.userButtonShare: "Share to other",
  LangKey.userTabNewFeatures: "New features",
  LangKey.userButtonLanguages: "Languages",
  LangKey.userButtonMusic: "Music",
  LangKey.userButtonSound: "Sound",
  LangKey.userButtonNotification: "Notification",
  LangKey.userButtonSwitch: "Switch account",
  LangKey.userButtonLogout: "Log out",
  LangKey.userButtonAddAccount: "Add new account",
  LangKey.trainNameOwn: "Balls",
  LangKey.tranMeanTask:
      "Daily Task", // 注意：这里可能是LangKey的名称拼写错误，应该是LangKey.trainMeanTask
  LangKey.newsTabGame: "Game news",
  LangKey.newsTabSchedule: "Schedule",
  LangKey.newsTabInjuries: "Injuries",
  LangKey.newsTabDraft: "Draft",
  LangKey.newsTabStreakPick: "Today's Streak Picks",
  LangKey.newsTabTrade: "Trade",
  LangKey.newsTabRumor: "Top Rumor",
  LangKey.newsTabPopular: "Popular player",
  LangKey.newsTabLastest: "Lastest", // 校正拼写："Lastest" 应该是 "Latest"
  LangKey.newsNameTp: "3 Points",
  LangKey.pickTabTask: "Daily Task",
  LangKey.pickTipsTask: "Select {0} player can get the reward",
  LangKey.pickButtonCheck: "Check Line Up",
  LangKey.pickButtonGo: "Go",
  LangKey.teamButtonNotice: "Notices",
  LangKey.teamTabGift: "Free Gift",
  LangKey.teamButtonGift: "Receive",
  LangKey.teamButtonBattlePass: "Trophy Road",
  LangKey.teamButtonUnlocked: "Unlocked",
  LangKey.teamButtonGoMatch: "Go To Match",
  LangKey.teamTabMatch: "MATCH GAME",
  LangKey.teamButtonMatch: "MATCH",
  LangKey.teamTabTrainLevel: "DEGREE OF TRAINING",
  LangKey.teamTabTrainBuff: "TRAINING BUFF",
  LangKey.teamTabTrain: "TRAINING",
  LangKey.teamTipsBuffNone: "NONE",
  LangKey.teamButtonStart: "START",
  LangKey.teamTabTeamPower: "TEAM POWER",
  LangKey.teamButtonLineUp: "LINE UP",
  LangKey.gameTabManager: "Manager",
  LangKey.gameTabMe: "me",
  LangKey.pickNameTotalPoints: "Total Points",
  LangKey.pickNameTotalRebounds: "Total Rebounds",
  LangKey.pickNameTotalAssists: "Total Assits", // 校正拼写错误："Assits" 应为 "Assists"
  LangKey.pickNameTotalPNA: "Total Points+Assists",
  LangKey.pickButtonEdit: "pickButtonClear",
  LangKey.pickTipsAdd: "Add player pick",
  LangKey.pickNameCost: "Wager",
  LangKey.pickButtonDone: "Done",
  LangKey.pickTipsSuccess: "PICK SUCCESS",
  LangKey.pickButtonContinue: "CONTINUE",
  LangKey.scoreTipsFinal: "Final",
  LangKey.scoreTipsResult: "Result",
  LangKey.gameInfoCongratulation: "CONGRATULATION",
  LangKey.gameInfoGetJetton: "You have won {0} jetton",
  LangKey.scoreTipsGaming: "Gaming",
  LangKey.scoreButtonWin: "WIN",
  LangKey.scoreTipsRate: "Support rate",
  LangKey.nbaTeamMeanOverview: "OVERVIEW",
  LangKey.nbaTeamMeanRoster: "ROSTER",
  LangKey.nbaTeamMeanStats: "STATS",
  LangKey.nbaTeamMeanLog: "LOG",
  LangKey.nbaTeamMeanEastern: "IN EASTERN",
  LangKey.nbaTeamMeanWestern: "IN WESTERN",
  LangKey.nbaTeamTabAvg: "Season Avg",
  LangKey.nbaTeamNamePpg: "PPG",
  LangKey.nbaTeamNameRpg: "RPG",
  LangKey.nbaTeamNameApg: "APG",
  LangKey.nbaTeamNameOppg: "OPPG",
  LangKey.nbaTeamTabOppg: "RECENT",
  LangKey.nbaTeamTabOutcome: "OUTCOME",
  LangKey.pickTipsReview: "Post your prediction",
  LangKey.nbaTeamMeanForward: "FORWARD",
  LangKey.nbaTeamMeanGuard: "GUARD",
  LangKey.nbaTeamMeanCenter: "CENTER",
  LangKey.nbaTeamMeanPlayerCount: "PLAYER COUNT",
  LangKey.nbaTeamMeanLeader: "TEAM LEADERS",
  LangKey.nbaTeamMeanTeamStats: "TEAM STATS",
  LangKey.nbaTeamMeanOvr: "OVR",
  LangKey.nbaTeamMeanHome: "HOME",
  LangKey.nbaTeamMeanAway: "AWAY",
  LangKey.gameStatsMeanExhausted: "Exhausted",
  LangKey.gameStatsMeanTired: "Tired",
  LangKey.gameStatsMeanNormal: "Normal",
  LangKey.gameStatsMeanGood: "Good",
  LangKey.gameStatsMeanEnergetic: "Energetic",
  LangKey.gameStatsMeanBoundless: "Boundless",
  LangKey.gameMeanRegular: "REG",
  LangKey.gameMeanPost: "POS",
  LangKey.gameMeanCareer: "CAREER",
  LangKey.gameNameAvg: "AVG",
  LangKey.gameName: "HT",
  LangKey.gameNameWt: "WT",
  LangKey.gameTabInbox: 'Inbox',
  LangKey.gameTabWaiting: 'Waiting',
  LangKey.gameMeanPlayerDate: 'PlAYER DATE',

  ///286
  LangKey.gameMeanPower: "POWER",
  LangKey.gameMeanSalary: "SALARY",
  LangKey.gameMeanPass: "PASS",
  LangKey.gameMeanSkill: "SKILL",
  LangKey.gameMeanOffensive: "OFFENSIVE",
  LangKey.gameMeanAdditional: "ADDITIONAL",
  LangKey.gameMeanLayUp: "LAYUP",
  LangKey.gameMeanMidRange: "MID-RANGE",
  LangKey.gameMeanThreePoint: "3-POINT",
  LangKey.gameMeanJumpShot: "JUMP SHOT",
  LangKey.gameMeanPaintDefence: "PAINT DEFENCE",
  LangKey.gameMeanOutsideDefence: "OUTSIDE DEFENCE",
  LangKey.gameMeanSelectPlayer: "SELECT PLAYER",
  LangKey.gameLittleNameStar: "star",
  LangKey.gameLittleNameGrade: "grade",
  LangKey.gameMeanScriPlayer: "Add Scrimmage Player",
  LangKey.gameMeanStarUpSuccess: "Star Up Success",
  LangKey.gameNamePow: "POW",
  LangKey.gameNamePlayerNumber: "Number",
  LangKey.gameButtonFinish: "Finish",
  LangKey.gameTipsTimes: "TIMES",
  LangKey.gameTipsStarSuccess: "STAR UP SUCCEEDED",
  LangKey.gameTipsStarFailed: "STAR UP FAILED",

  ///309
  LangKey.gameTabFreeAgency: "FREE AGENCY",
  LangKey.gameTabPlayerOvr: "Player OVR",
  LangKey.gameTabPosition: "Position",
  LangKey.gameTabNbaTeam: "Teams",
  LangKey.gameButtonReset: "RESET",
  LangKey.gameButtonDelete: "FIRE",
  LangKey.gameButtonCancel: "CANCEL",
  LangKey.gameTabFire: "FIRE THE PLAYER",
  LangKey.gameTipsFire: "Are you sure fire {0}",
  LangKey.gameTipsFireReward: "You can get",
  LangKey.pickTabMyRank: "MY RANK",
  LangKey.pickTipsNoReward: "NO REWARD",
  LangKey.pickTipsRank: "Win {0} coins can earn a ranking",
  LangKey.pickTipsRankRule:
      "The ranking is determined by the profits earned during the open and close periods of each leaderboard cycle",
  LangKey.pickTabTips: "TIPS",
  LangKey.pickTabsAddPick: "Add a pick combo",
  LangKey.gameTipsConsumed: "The selected player will be consumed",
  LangKey.gameButtonSkip: "SKIP",
  LangKey.gameButtonSeeAll: "SEE ALL",
  LangKey.gameButtonWinRate: "WIN RATE TREND",
  LangKey.gameTabTotal: "Total",
  LangKey.gameTabGameLeader: "GAME LEADER",
  LangKey.gameTabPoints: "POINTS",
  LangKey.gameTabRebounds: "REBOUNDS",
  LangKey.gameTabAssists: "ASSISTS",
  LangKey.gameTabStarter: "STARTER",
  LangKey.gameTabBench: "BENCH",
  LangKey.gameTabAddBility: 'ADD ABILITY',
  LangKey.teamTipsAddPlayer: 'Add a player',

  //338
  LangKey.dailyTaksTab: "DAILY TASK",
  LangKey.dailyTaksButtonSpin: "SPIN",
  LangKey.dailyTaksTabMyReward: "My Reward",
  LangKey.dailyTaksButtonCAE: "CLAIM AND EXIT",
  LangKey.dailyTaksTipsCAE: "Claim the earned rewards and exit the wheel",
  LangKey.dailyTaksTipsExit:
      "There are still many generous rewards to come. Are you sure to exit",
  LangKey.dailyTaksButtonPlayOn: "PLAY ON",
  LangKey.dailyTaksMeanWeekReward: "Week Prize",
  LangKey.dailyTaksButtonGet: "GET",
  LangKey.dailyTaksTabGet: "YOU'RE OUT",
  LangKey.dailyTaksTipsGet:
      "If you exit now, you will lose all the rewards. It is recommended that you use {0} to continue the wheel",
  LangKey.dailyTaksButtonGiveUp: "QUIT",
  LangKey.dailyTaksTabGiveUp: "YOU'LL LOSE THESE REWARDS",
  LangKey.dailyTaksTipsGiveUp:
      "These are the rewards you have accumulated so far",
  LangKey.dailyTaksTabClaim: "ALL REWARDS CLEARED",
  LangKey.dailyTaksTabBigPrize: "Big Prize",
  LangKey.dailyTaksTabPrizePool: "Prize Pool",
  LangKey.gameNamePG: "PG",
  LangKey.gameNameSG: "SG",
  LangKey.gameNameSF: "SF",
  LangKey.gameNamePF: "PF",
  LangKey.gameNameC: "C",
  LangKey.gameTabSkip: "SKIP THE GAME",
  LangKey.gameTipsSkip: "Are you sure you want to skip the play-by-play?",
  LangKey.gameMeanSkip: "STATUS",
  LangKey.gameMeanRating: "RATING",
  LangKey.gameButtonUnfold: "UNFOLD",
  LangKey.gameTipsTrophiesRisen: "The number of trophies has risen",
  LangKey.gameTipsTrophiesDropped: "The number of trophies has dropped",
  // 367
  LangKey.gameNamePPG: "PPG",
  LangKey.gameNameRPG: "RPG",
  LangKey.gameNameAPG: "APG",
  LangKey.gameMeanTPM: "THREE-POINT MAKES",
  LangKey.gameBigNameFGP: "FIELD GOAL PERCENTAGE",
  LangKey.gameBigNameFTM: "FREE THROW MAKES",
  LangKey.gameNameFTP: "FT%",
  LangKey.gameNameTPG: "TPG",
  LangKey.gameBigNameFT: "FREE THROW PERCENT",
  LangKey.gameBigNameFTA: "FREE THROW ATTEMPT",
  LangKey.gameBigNameTO: "TURNOVERS",
  LangKey.gameNameGP: "GP",
  LangKey.gameNameFT: "FT",
  LangKey.gameNameDREB: "DREB",
  LangKey.gameNameFPG: "FPG",
  LangKey.gameNameMIN: "MIN",
  LangKey.gameNameOREB: "OREB",
  LangKey.gameNamePtsAst: 'PTS+AST',
  LangKey.gameNamPtsReb: 'PTS+REB',
};

// const Map<String, String> en_US = {
//   'news': 'NEWS',
//   'picks': 'PICKS',
//   'team': 'TEAM',
//   'leagues': 'LEAGUES',
//   "gameNameFgm": "FGM",
//   'gameNameFga': 'FGA'
// };
