import 'package:arm_chair_quaterback/common/langs/lang_key.dart';

Map<String, String> zh_CN = {
  LangKey.gameNameFgm: "两分命中数",
  LangKey.gameNameFga: "两分出手数",
  LangKey.gameNameTgm: "三分命中数",
  LangKey.gameNameTga: "三分出手数",
  LangKey.gameNameFtm: "罚球命中数",
  LangKey.gameNameFta: "罚球出手数",
  LangKey.gameNameReb: "篮板",
  LangKey.gameNameAst: "助攻",
  LangKey.gameNameStl: "抢断",
  LangKey.gameNameBlk: "盖帽",
  LangKey.gameNameFoul: "犯规",
  LangKey.gameNameTo: "失误",
  LangKey.gameNamePts: "得分",
  LangKey.gameTabNews: "新闻",
  LangKey.gametabPicks: "竞猜",
  LangKey.gametabStocks: "交易行",
  LangKey.gametabTeam: "队伍",
  LangKey.gametabScores: "赛程",

  // 咨询1级 - 页签标题
  LangKey.newsTabTickers: "今日新闻",
  LangKey.newsTabNews: "新闻正文",
  LangKey.newsTabMore: "更多新闻（推荐）",
  LangKey.newsTabReview: "评论",
  LangKey.newsTipsInput: "说些什么吧",
  LangKey.newsButtonReply: "回复",
  LangKey.newsButtonMore: "展开",
  LangKey.newsButtonFold: "收起",
  LangKey.newsTipsFold: "没有更多了",
  LangKey.newsTabStats: "数据排行榜",
  LangKey.newsTabStanding: "排行榜",

  // 咨询2级 - 页签标题等
  LangKey.newsButtonPlayer: "球员数据",
  LangKey.newsButtonTeam: "球队数据",
  LangKey.newsTabRank: "排名",
  LangKey.gameMeanPts: "得分",
  LangKey.gameMeanAst: "助攻",
  LangKey.gameMeanBlk: "盖帽",
  LangKey.gameMeanFgp: "命中率",
  LangKey.gameMeanReb: "篮板",
  LangKey.gameMeanStl: "抢断",
  LangKey.gameMeanFtp: "罚球命中率",
  LangKey.gameMeanTpp: "三分命中率",
  LangKey.gameMeanTo: "失误",
  LangKey.gameMeanReseason: "常规赛",
  LangKey.gameMeanPoseason: "季后赛",
  LangKey.newsButtonEastern: "东部",
  LangKey.newsButtonWestern: "西部",
  LangKey.newsTabType: "数据类型",
  LangKey.newsTabSeason: "赛季",

  // 竞猜1级 - 页签标题
  LangKey.pickTabRank: "竞猜排行榜",
  LangKey.pickTabHistory: "历史记录",
  LangKey.pickTabRewards: "竞猜奖励界面",
  LangKey.pickTabMnl: "猜多猜少",
  LangKey.pickButtonMore: "更多",
  LangKey.pickButtonLess: "更少",
  LangKey.pickButtonConfirm: "确认",

  // 竞猜2级 - 名词定义等
  LangKey.pickWinTimes: "竞猜胜利场次",
  LangKey.pickSuccess: "竞猜成功率",
  LangKey.gameTapPick: "竞猜情况",
  LangKey.gameTapTeam: "阵容情况",
  LangKey.pickRankCon: "排行榜情况",
  LangKey.pickRankReward: "排行榜奖励",
  LangKey.pickrRankNum: "第{0}期排行榜",
  LangKey.pickrRankIntro: "选的多选的准（排行榜介绍文案）",
  LangKey.pickRankBox: "女神自选宝箱--奖励",
  LangKey.pickRankCoin: "竞猜币/筹码--奖励",
  LangKey.pickTapRankRaward: "排行榜奖励",
  LangKey.pickButtonGet: "领取奖励",
  LangKey.pickButtonReceiveAll: "一键领取",
  LangKey.pickTapRank: "排名",
  // 个人信息
  LangKey.userButtonProfile: "个人信息",
  LangKey.userButtonMessage: "消息",
  LangKey.userButtonSetting: "设置",
  LangKey.userButtonAccount: "账户",
  LangKey.userNameTeamLevel: "球队等级",
  LangKey.userNameWinRate: "球队胜率",
  LangKey.userNameWinTimes: "累计胜场",
  LangKey.userNameWinStreak: "最高连胜",
  LangKey.userNameCurrentCup: "当前（杯数）",
  LangKey.userNameBestCup: "最高（杯数）",
  LangKey.userNamePickHistory: "待开奖竞猜队列",
  LangKey.userNameStreakPick: "竞猜累计胜场",
  LangKey.uesrNameNewsPick: "已开奖的竞猜队列",
  LangKey.uesrNameLastInterrupt: "上一次连胜记录",
  LangKey.userNameNick: "玩家昵称",
  LangKey.userNameBirthday: "玩家生日",
  LangKey.userNameAbout: "自我介绍",
  LangKey.userButtonSave: "保存",
  LangKey.userButtonReport: "举报",
  LangKey.userButtonBlock: "拉黑",
  LangKey.userButtonRelease: "取消拉黑",
  LangKey.userButtonShare: "分享玩家",
  LangKey.userTabNewFeatures: "新功能",
  LangKey.userButtonLanguages: "语言",
  LangKey.userButtonMusic: "背景音乐",
  LangKey.userButtonSound: "音效",
  LangKey.userButtonNotification: "系统通知",
  LangKey.userButtonSwitch: "切换账号",
  LangKey.userButtonLogout: "退出登录",
  LangKey.userButtonAddAccount: "增加新账号",

  // NBA球队详情2级 - 名词定义等
  LangKey.nbaTeamMeanOverview: "球队详情概览",
  LangKey.nbaTeamMeanRoster: "球员名单",
  LangKey.nbaTeamMeanStats: "球队数据",
  LangKey.nbaTeamMeanLog: "球队对阵日志",
  LangKey.nbaTeamMeanEastern: "东部",
  LangKey.nbaTeamMeanWestern: "西部",
  LangKey.nbaTeamTabAvg: "赛季平均值",
  LangKey.nbaTeamNamePpg: "赛季场均得分",
  LangKey.nbaTeamNameRpg: "赛季场均篮板",
  LangKey.nbaTeamNameApg: "赛季场均助攻",
  LangKey.nbaTeamNameOppg: "对手场均得分",
  LangKey.nbaTeamTabOppg: "最近表现",
  LangKey.nbaTeamTabOutcome: "球队往期竞猜结果",

// 游戏系统 - 名词定义等
  LangKey.gameStatsMeanExhausted: "状态-非常疲惫",
  LangKey.gameStatsMeanTired: "状态-一点累",
  LangKey.gameStatsMeanNormal: "状态-一般",
  LangKey.gameStatsMeanGood: "状态-不错",
  LangKey.gameStatsMeanEnergetic: "状态-精力充沛",
  LangKey.gameStatsMeanBoundless: "状态-精力爆表",
  LangKey.gameMeanRegular: "常规赛缩写",
  LangKey.gameMeanPost: "季后赛缩写",
  LangKey.gameMeanCareer: "生涯",
  LangKey.gameNameAvg: "平均值",
  LangKey.gameNameHeight: "身高",
  LangKey.gameNameWeight: "体重",
  LangKey.gameNameExp: "NBA时长",

  // 球队1级 - 按钮名称、页签标题等
  LangKey.teamButtonNotice: "消息",
  LangKey.teamTabGift: "免费礼物",
  LangKey.teamButtonGift: "点击领取",
  LangKey.teamButtonBattlePass: "奖杯之路",
  LangKey.teamButtonUnlocked: "点击解锁",
  LangKey.teamButtonGoMatch: "前往匹配",
  LangKey.teamTabMatch: "匹配赛",
  LangKey.teamButtonMatch: "匹配",
  LangKey.teamTabTrainLevel: "训练程度",
  LangKey.teamTabTrainBuff: "特训BUFF",
  LangKey.teamTabTrain: "训练",
  LangKey.teamTipsBuffNone: "空缺",
  LangKey.teamButtonStart: "开始训练",
  LangKey.teamTabTeamPower: "球队战力",
  LangKey.teamButtonLineUp: "阵容",
  LangKey.gameTabManager: "经理",
  LangKey.gameTabMe: "我的排名",
  LangKey.pickNameTotalPoints: "总得分",
  LangKey.pickNameTotalRebounds: "总篮板",
  LangKey.pickNameTotalAssists: "总助攻",
  LangKey.pickNameTotalPNA: "总得分+助攻",
  LangKey.pickButtonEdit: "编辑注单",
  LangKey.pickTipsAdd: "增加下注球员",
  LangKey.pickNameCost: "下注金额",
  LangKey.pickButtonDone: "完成",
  LangKey.pickTipsSuccess: "成功下注",
  LangKey.pickButtonContinue: "继续",
  LangKey.scoreTipsFinal: "比赛结束",
  LangKey.scoreTipsResult: "结果",
  LangKey.gameInfoCongratulation: "恭喜",
  LangKey.gameInfoGetJetton: "你赢的了{0}个筹码",
  LangKey.scoreTipsGaming: "比赛中",
  LangKey.scoreButtonWin: "获胜",
  LangKey.scoreTipsRate: "支持率",

  // NBA球队详情2级 - 名词定义等（续）
  LangKey.nbaTeamMeanForward: "锋线",
  LangKey.nbaTeamMeanGuard: "后卫",
  LangKey.nbaTeamMeanCenter: "中锋",
  LangKey.nbaTeamMeanPlayerCount: "数据统计",
  LangKey.nbaTeamMeanLeader: "球队大佬",

  // 竞猜--弹窗 - 提示、名词定义等
  LangKey.pickTipsFlex: "{0}个球员中需要选对{0}个",
  LangKey.pickButtonClear: "删除全部",
  LangKey.pickTipsLackMoney: "钞票不足",
  LangKey.pickNameResult: "数据结果",
  LangKey.pickNameProcess: "开奖中",

  // 训练1级 - 名词定义等
  LangKey.trainNameOwn: "我的篮球",
  LangKey.tranMeanTask: "任务",

  // 咨询1级 - 页签标题等
  LangKey.newsTabGame: "赛事",
  LangKey.newsTabSchedule: "赛事日程",
  LangKey.newsTabInjuries: "伤病通知",
  LangKey.newsTabDraft: "选秀新闻",
  LangKey.newsTabStreakPick: "今日竞猜-连胜玩法",
  LangKey.newsTabTrade: "交易",
  LangKey.newsTabRumor: "谣言",
  LangKey.newsTabPopular: "热门球员",
  LangKey.newsTabLastest: "最新",
  LangKey.newsNameTp: "3分",

  // 竞猜1级 - 页签标题等
  LangKey.pickTabTask: "每日任务",
  LangKey.pickTipsTask: "选择{0}个球员可以获得奖励",
  LangKey.pickButtonCheck: "我的下注队列",
  LangKey.pickButtonGo: "前往",

  // 游戏系统 - 名词定义等（续）
  LangKey.gameNameJetton: "竞猜币/筹码",
  LangKey.gameFullNamePts: "场均得分",
  LangKey.gameFullNameAst: "场均助攻",
  LangKey.gameFullNameReb: "场均篮板",
  LangKey.gameFullNameFGP: "场均命中率",
  LangKey.gameFullNameBlk: "场均盖帽",
  LangKey.gameFullNameStl: "场均抢断",
  LangKey.gameFullNameFtp: "场均罚篮命中率",
  LangKey.gameFullNameTpa: "场均三分出手数",
  LangKey.gameFullNameTpp: "三分命中率",
  LangKey.gameFullNameTo: "场均失误",

  // 游戏系统 - 名词定义等（续）
  LangKey.managerHi: "Hi,{玩家昵称}",
  LangKey.managerTipsIntro1: "今日你还未开始比赛",
  LangKey.managerTipsIntro2: "今日你的赛事记录",
  LangKey.managerNameBattleTimes: "比赛",
  LangKey.managerNameTrainingTimes: "训练",
  LangKey.cardpackButtonOpen: "打开",
  LangKey.tieButtonOpen: "羁绊",
  LangKey.managerNameTrainingLevel: "训练程度",
  LangKey.managerTabTeam: "球队",
  LangKey.managerTabMyTeam: "我的球队",
  LangKey.teamTabLineUp: "阵容",
  LangKey.teamTabPlayerBag: "背包",
  LangKey.gameNameOvr: "球队实力排名",
  LangKey.gameMeanSalaryCap: "工资帽",
  LangKey.gameMeanTeamStamina: "球队体力值",
  LangKey.teamTipsRest: "球队恢复1次体力",
  LangKey.teamMeanMain: "主力",
  LangKey.playerNameSalary: "薪资",
  LangKey.playerNameStamina: "体力",
  LangKey.playerButtonAddStamina: "恢复体力",
  LangKey.teamMeanSubstitiute: "替补",
  LangKey.teamNameSubstitiute: "替补",
  LangKey.teamButtonAddPlayer: "上阵球员",
  LangKey.teamTipsUnlcok: "球队{0}级解锁",
  LangKey.teamTabsAddStamina: "恢复体力",
  LangKey.teamTipsTeamRest: "倒计时结束全队将恢复1次体力，你想要提前恢复体力吗",
  LangKey.teamMeanCost: "消耗",
  LangKey.managerTabCardPack: "胜利卡包",
  LangKey.gameNameTp: "3分",
  LangKey.gameMeanMe: "我方",
  LangKey.gameMeanOpp: "敌方",
  LangKey.gameMeanRate: "胜负趋势",
  LangKey.gameNameSt: "第一节",
  LangKey.gameNameNd: "第二节",
  LangKey.gameNameRd: "第三节",
  LangKey.gameNameTh: "第四节",
  LangKey.gameMeanPlayer: "球员数据",
  LangKey.gameMeanTeam: "球队数据",
  LangKey.gameButtonback: "返回",
  LangKey.gameMeanTrade: "今日交易金额",
  LangKey.gameMeanPrice: "球员身价",
  LangKey.gameNameBag: "球员背包",
  LangKey.gameTabBuy: "买入球员",
  LangKey.gameTabSell: "卖出球员",
  LangKey.gameButtonBuy: "买入球员",
  LangKey.gameButtonSell: "卖出球员",
  LangKey.gameTabPlayerInfo: "详情",
  LangKey.gameNameAge: "年龄",
  LangKey.gameTabSummary: "总结",
  LangKey.gameTabLogs: "日志",
  LangKey.gameTabGame: "游戏",
  LangKey.gameTabL5: "最近5场数据",
  LangKey.gameTabSeasonAvg: "赛季平均值",
  LangKey.gameTabL5Avg: "L5平均值",
  LangKey.gameTabBetSelection: "竞猜选择",
  LangKey.gameTabGameGrade: "球员游戏品阶",
  LangKey.gameMeanSeasonAvg: "赛季平均值",
  LangKey.gameNameScore: "球员评分",
  LangKey.gameButtonStarUp: "升星",
  LangKey.gameNameAbility: "球员能力",
  LangKey.gameNamePotential: "球员潜力",
  LangKey.gameNameSuccess: "升星成功概率",
  LangKey.gameNameGrade: "球员品阶",
  LangKey.gameNameStar: "球员星级",
  LangKey.gameNameSelected: "已选择球员",
  // 球员详情2级 - 名词定义等（续）
  LangKey.gameTabSuccess: "升星成功",
  LangKey.gameTabFail: "升星失败",
  LangKey.pickTabLineUp: "竞猜队列",
  LangKey.pickMeanFlex: "普通模式",
  LangKey.pickMeanPower: "强绑定模式",
  LangKey.pickNameCorrect: "正确",
  LangKey.pickNameSelected: "已选项数",
  LangKey.pickNameToWin: "胜利可得金额",
  LangKey.pickNameStreak: "连胜次数",
  LangKey.pickNameStreakBonus: "连胜奖金",

  // NBA球队详情2级 - 名词定义等（续）
  LangKey.nbaTeamMeanTeamStats: "球队数据",
  LangKey.nbaTeamMeanOvr: "排行",
  LangKey.nbaTeamMeanHome: "主场",
  LangKey.nbaTeamMeanAway: "客场",

  // 游戏系统 - 名词定义等（续）
  LangKey.gameName: "身高",
  LangKey.gameNameWt: "体重",
  LangKey.gameTabInbox: "消息",
  LangKey.gameTabWaiting: "等待中...",
  LangKey.gameMeanPlayerDate: "图鉴",

  ///286-308
  LangKey.pickTapBenefits: '盈利',
  LangKey.gameMeanPower: "能力值",
  LangKey.gameMeanSalary: "工资",
  LangKey.gameMeanPass: "传球",
  LangKey.gameMeanSkill: "技巧",
  LangKey.gameMeanOffensive: "进攻",
  LangKey.gameMeanAdditional: "球员属性",
  LangKey.gameMeanLayUp: "上篮",
  LangKey.gameMeanMidRange: "中距离投篮",
  LangKey.gameMeanThreePoint: "三分球",
  LangKey.gameMeanJumpShot: "跳投",
  LangKey.gameMeanPaintDefence: "内线防守",
  LangKey.gameMeanOutsideDefence: "外线防守",
  LangKey.gameMeanSelectPlayer: "选择球员",
  LangKey.gameLittleNameStar: "星级",
  LangKey.gameLittleNameGrade: "评分",
  LangKey.gameMeanScriPlayer: "添加训练赛球员",
  LangKey.gameMeanStarUpSuccess: "升星成功率",
  LangKey.gameNamePow: "力量",
  LangKey.gameNamePlayerNumber: "已选球员数量",
  LangKey.gameButtonFinish: "完成",
  LangKey.gameTipsTimes: "次数",
  LangKey.gameTipsStarSuccess: "升星成功",
  LangKey.gameTipsStarFailed: "升星失败",

  ///309
  LangKey.gameTabFreeAgency: "自由球员",
  LangKey.gameTabPlayerOvr: "球员排名",
  LangKey.gameTabPosition: "球员位置",
  LangKey.gameTabNbaTeam: "球队",
  LangKey.gameButtonReset: "重置",
  LangKey.gameButtonDelete: "删除",
  LangKey.gameButtonCancel: "取消",
  LangKey.gameTabFire: "解雇球员确认",
  LangKey.gameTipsFire: "你确认解雇 {0}",
  LangKey.gameTipsReward: "你将获得",
  LangKey.pickTabMyRank: "我的排名",
  LangKey.pickTipsNoReward: "未获得奖励",
  LangKey.pickTipsRank: "赢得 {0} 筹码可以上榜",
  LangKey.pickTipsRankRule: "根据每期排行榜开启和关闭时间段内的盈利决定排名",
  LangKey.pickTabTips: "提示",
  LangKey.pickTabsAddPick: "增加一个竞猜选择作为组合",
  LangKey.gameTipsConsumed: "选中的球员升星结束后会被消耗掉",
  LangKey.gameButtonSkip: "跳过比赛",
  LangKey.gameButtonSeeAll: "查看全部",
  LangKey.gameButtonWinRate: "胜率趋势",
  LangKey.gameTabTotal: "汇总",
  LangKey.gameTabGameLeader: "本场优秀球员",
  LangKey.gameTabPoints: "得分",
  LangKey.gameTabRebounds: "篮板",
  LangKey.gameTabAssists: "助攻",
  LangKey.gameTabStarter: "首发",
  LangKey.gameTabBench: "板凳",
  LangKey.gameTabAddBility: '升星增加的能力'
};
